Music for a level
AztecGameLab/LongTermGame4 pull request #119
Opened 2020-10-20 03:00 UTC by JackedGandhi

This is a classical guitar sample loop that I think would fit nicely into a level, or maybe as a theme for another character/boss that may appear in the game.

2020-10-20 05:40 UTC, KyleMcLainKane requested changes
Hey what is the file called Ominous Classical Guitar Sample.wav.asd? I don't recognize that file extension type. Is this file intended to be in the project?

2020-10-20 05:52 UTC, JackedGandhi commented
Oh that's just the Ableton type file in case somebody wanted to work on it, but it actually won't be necessary since the wav file will suffice in this case, being that it's only an audio sample. I'll remove it.

2020-10-21 01:21 UTC, KyleMcLainKane reviewed
I removed the file

2020-10-21 01:22 UTC, KyleMcLainKane approved these changes

2020-10-21 01:23 UTC, merged